name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

deploy:
    runs-on: self-hosted  # Твой сервер сам заберет эту задачу
    needs: build-and-push
    steps:
      - name: Update containers
        run: |
          cd /home/kDst9/simpleapp  # Убедись, что путь правильный!
          # Логинимся, чтобы скачать приватный образ из GHCR
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker compose pull
          docker compose up -d
          docker system prune -f
